fix(test): Add missing `insta[yaml]` for recipe generator crate
Add the `yaml` feature for the `insta` dependency, as otherwise testing
`crates/rattler_build_recipe_generator` fails with:

```
error[E0432]: unresolved import `insta::assert_yaml_snapshot`
   --> crates/rattler_build_recipe_generator/src/pypi.rs:501:9
    |
501 |     use insta::assert_yaml_snapshot;
    |         ^^^^^^^--------------------
    |         |      |
    |         |      help: a similar name exists in the module: `assert_debug_snapshot`
    |         no `assert_yaml_snapshot` in the root

For more information about this error, try `rustc --explain E0432`.
```

Signed-off-by: Michał Górny <mgorny@quansight.com>